import { dog } from './dog';

export const dogS: dog[] = [
  {
    id: '3f94541b-2ac1-4497-be1c-b3b86facc9d3',
    name: 'dog #1',
    breed: 'Siberian Husky',
    color: 'blue',
    weight: 10,
    age: 1,
    location: 'Little Rock',
    gender: '',
    size: '',
    spayedNeutered: false,
    temperament: '',
    adoptionFee: 0,
    vaccinated: false,
    healthIssues: '',
    training: '',
    availabilityDate: new Date('2023-06-15'),
    photos: []
  },
  {
    id: '8bd8d6a8-132d-4342-8e93-731545f44afc',
    name: 'dog #2',
    breed: 'German Shepard',
    color: 'red',
    weight: 5,
    age: 1,
    location: 'North Little Rock',
    gender: '',
    size: '',
    spayedNeutered: false,
    temperament: '',
    adoptionFee: 0,
    photos: [],
    vaccinated: false,
    healthIssues: '',
    training: '',
    availabilityDate: new Date('2023-06-15'),
  },
  {
    id: '7a754667-80f0-4c36-b7d9-44e2adf05f87',
    name: 'dog #3',
    breed: 'Golden Retriever',
    color: 'green',
    weight: 15,
    age: 1,
    location: 'Conway',
    gender: '',
    size: '',
    spayedNeutered: false,
    temperament: '',
    adoptionFee: 0,
    photos: [],
    vaccinated: false,
    healthIssues: '',
    training: '',
    availabilityDate: new Date('2023-06-15'),
  },
  {
    id: 'c8af0168-d597-486b-a1f4-f65ea323f7e6',
    name: 'dog #4',
    breed: 'Labrador Retriever',
    color: 'yellow',
    weight: 12,
    age: 1,
    location: 'Conway',
    gender: '',
    size: '',
    spayedNeutered: false,
    temperament: '',
    adoptionFee: 0,
    photos: [],
    vaccinated: false,
    healthIssues: '',
    training: '',
    availabilityDate: new Date('2023-06-15'),
  },
  {
    id: '03c988de-ce5b-41d8-baba-c220c946a005',
    name: 'dog #5',
    breed: 'Australian Shepard',
    color: 'orange',
    weight: 24,
    age: 1,
    location: 'Little Rock',
    gender: '',
    size: '',
    spayedNeutered: false,
    temperament: '',
    adoptionFee: 0,
    photos: [],
    vaccinated: false,
    healthIssues: '',
    training: '',
    availabilityDate: new Date('2023-06-15'),
  },
];
